_:
  @just -l

flash-adb:
  PKG_CONFIG_SYSROOT_DIR=./cross-build-deps/aarch64 maturin build --out dist --interpreter python 3.12 --target aarch64-unknown-linux-gnu --zig --release
  adb push ./dist/do_daw-0.1.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl /userdata/roms/ports/dream-of-daw/
  adb shell /userdata/roms/ports/dream-of-daw/.venv/bin/python -m pip install --force-reinstall --no-index /userdata/roms/ports/dream-of-daw/do_daw-0.1.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl

kill-docs:
  #!/usr/bin/bash
  proc=$(ps aux | rg "python3 -m http.server" | rg -v "rg python3" | cut -d " " -f 4)
  kill $proc

docs-is-running:
  ps aux | rg "python3 -m http.server" | rg -v "rg python3"
  echo "if there is no output above, server is not running"  

server-docs:
  #!/usr/bin/bash
  proc=$(ps aux | rg "python3 -m http.server" | rg -v "rg python3" | cut -d " " -f 4)
  dir=$(pwdx $proc 2> /dev/null | cut -d ' ' -f 2)

  if [[ -z $proc ]]; then
    echo "no docs server found; RUNNING"
    # nohup python3 -m http.server -b 127.0.0.1 -d ./target/doc 8080 > /dev/null &
    nohup python3 -m http.server -d ./target/doc 8080 > /dev/null &
    echo "docs-server process: $(ps aux | rg "python3 -m http.server" | rg -v "rg python3" | cut -d " " -f 4)"
  elif [[ $dir == $PWD && -n $dir ]]; then
    echo "server found to be already running; NOT RUNNING"
    echo "docs server running in: $dir"
    echo "docs-server process: $proc"
  else
    echo "docks server running in another directory; won't disturb"
    echo "docs server running in: $dir"
    echo "docs-server process: $proc"
  fi

open-docs:
  $BROWSER localhost:8080

[parallel]
docs: server-docs open-docs
