_:
  @just -l

flash-adb:
  PKG_CONFIG_SYSROOT_DIR=./cross-build-deps/aarch64 maturin build --out dist --interpreter python 3.12 --target aarch64-unknown-linux-gnu --zig --release
  adb push ./dist/do_daw-0.1.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl /userdata/roms/ports/dream-of-daw/
  adb shell /userdata/roms/ports/dream-of-daw/.venv/bin/python -m pip install --force-reinstall --no-index /userdata/roms/ports/dream-of-daw/do_daw-0.1.0-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
